USE ARTEXHIBITION;
SELECT * FROM ARTWORK;
SELECT * FROM GALLERY;
SELECT * FROM EXHIBITION;
SELECT * FROM CONTACTS;
SELECT * FROM ARTIST;
SELECT * FROM CUSTOMER;
SELECT * FROM VISITS;
SELECT * FROM PARTICIPATES;
SELECT * FROM BOUGHT_BY;

