create database ArtExhibition;
use ArtExhibition;

 DELIMITER $$ 
              CREATE TRIGGER UPPERCASE 
              BEFORE INSERT on Gallery 
              FOR EACH ROW 
              BEGIN 
              SET NEW.gname=UPPER(NEW.gname); 
              END$$ 
  


 CREATE TABLE GALLERY(GID VARCHAR(20) PRIMARY KEY,
 GNAME CHAR(20),             
 LOCATION CHAR(20)); 
 

 CREATE TABLE EXHIBITION (EID VARCHAR(20) PRIMARY KEY, GID VARCHAR(20), 
 E_NAME CHAR(20), LOCATION CHAR(20),
 STARTDATE DATE, ENDDATE DATE, FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE CASCADE); 
 

 CREATE TABLE CUSTOMER(CUSTID VARCHAR(20) PRIMARY KEY,   
	FNAME CHAR(20),    LNAME CHAR(20), 
    DOB DATE, ADDRESS CHAR(20));
    

  CREATE TABLE ARTIST (ARTISTID VARCHAR(20) PRIMARY KEY,        
   GID VARCHAR(20), 
   FNAME CHAR(20), 
   LNAME CHAR(20), BIRTHPLACE CHAR(20),STYLE CHAR(20),
   FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE CASCADE); 
   

  CREATE TABLE ARTWORK(ARTID VARCHAR(20) PRIMARY KEY, TITLE VARCHAR(20), YEAR INT,            
  TYPE_OF_ART VARCHAR(20), PRICE INT,  EID VARCHAR(20), GID VARCHAR(20), ARTISTID varchar(20), 
  FOREIGN KEY(ARTISTID) REFERENCES ARTIST(ARTISTID) ON DELETE CASCADE, 
  FOREIGN KEY(EID) REFERENCES EXHIBITION(EID) ON DELETE CASCADE, 
  FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE CASCADE); 
  

    CREATE TABLE CONTACTS(CUSTID VARCHAR(20),        
    PHONE VARCHAR(12),   
    FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID) ON DELETE CASCADE);   


    CREATE TABLE BOUGHT_BY(CUSTID VARCHAR(20),ARTID VARCHAR(20),
    foreign key (CUSTID) references CUSTOMER(CUSTID), 
    foreign key (ARTID) references ARTWORK(ARTID));
    
  
    CREATE TABLE VISITS(CUSTID VARCHAR(20),EID VARCHAR(20),
    foreign key (CUSTID) references CUSTOMER(CUSTID),
    foreign key (EID) references EXHIBITION(EID));
    
  
    CREATE TABLE PARTICIPATES(EID VARCHAR(20),ARTISTID VARCHAR(20),
    foreign key (ARTISTID) references ARTIST(ARTISTID),
    foreign key (EID) references EXHIBITION(EID));
    
    drop database ArtExhibition;